/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  STORY SHOT STUDIO — UNIVERSAL SCENE ANALYZER  v3.0                    ║
 * ║  Culture-agnostic, era-agnostic, format-agnostic                       ║
 * ║  Supports: documentary narration, script blocks, structured text        ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

import type { SceneCard, Character, Location, TimeContext, NarrativeLayer } from '@/types';
import { aiProvider } from './aiProvider';

// ─────────────────────────────────────────────────────────────────────────────
// § 1  SCENE ANALYSIS SYSTEM PROMPT
//      Completely language and culture neutral.
//      Era, geography, and cultural context are always read from the text —
//      never assumed from a default (no "Ottoman", no "Anatolian", no "Turkish").
// ─────────────────────────────────────────────────────────────────────────────

export function getSceneAnalysisSystemPrompt(): string {
  return `You are a world-class documentary film director and visual editor.
The text you receive is a documentary voice-over narration or screenplay visual block.
Your task: analyse it and produce a structured list of visual scene cards.

Each scene card = ONE image = 3–5 seconds of screen time.
Images will be generated by AI tools and then animated.

SCENE COUNT FORMULA (CRITICAL — CALCULATE FIRST):
1. Estimate word count BEFORE processing.
2. Formula: word_count ÷ 5 = target scene count (unless a specific target is provided in the user message).
3. Aim for high density of scenes. 
4. Hit the requested target exactly. Under-producing is acceptable. Over-producing is not.`;
}

export function getSceneAnalysisTargetInstruction(targetSceneCount: number): string {
  return `🎯 TARGET: Produce EXACTLY ${targetSceneCount} scenes (tolerance: ±1).

This target is CRITICAL and overrides all other density rules.
- If the text is dense: merge secondary details to fit the count.
- If the text is sparse: split single sentences into multiple visual moments or focus on background details.
- Plan your ${targetSceneCount} beats before writing JSON.`;
}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SPLITTING LOGIC
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CORE RULE: One visual moment = one scene.
~4-5 source words → 1 scene. Even a 4-word phrase is a valid scene.

THESE ARE ALWAYS SEPARATE SCENES:
  • Each subject-action pair ("the caravans move" / "the camels slow")
  • Each comma-separated list item (location A / location B / location C)
  • Each "some...others..." or "while...meanwhile..." branch
  • Each emotional moment (reaction, realisation, grief, joy)
  • Each location transition
  • Each change of subject (crowd → individual → child)
  • Each change of action (reading → walking → praying)
  • A single object receiving focus ("his hand on the door")
  • Close-up-scale physical details ("the first drop on the lips")

TIMELAPSE SCENES:
  Phrases like "over centuries", "through the ages", "generation by generation",
  "slowly", "gradually" → mark as timelapse. Set visualNote prefix: "timelapse:"
  Example: "timelapse: temple silhouette across night-to-day cycle"
  Timelapse scenes count as ONE scene in the total.

MERGE ONLY IF:
  A single-word conjunction ("And", "But", "Then") with no image of its own
  may be merged into the preceding scene. No other merging.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VISUAL NOTE STANDARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The visualNote describes EXACTLY what the camera sees — physical and concrete.
Maximum 12 words. ALWAYS in TURKISH regardless of source text language.

CINEMATIC VANTAGE POINT — always specify the camera position/angle:
  • Omuz üstü, siluet, alt açı, yüksek açı, ayrıntıya odak, yansıma, pencerenin ardı
  • "Adam yürüyor" DEĞİL → "Omuz üstü: adamın gölgesi çamur zeminde uzayıp gidiyor"

WITNESSING QUALITY — frame as if spying on a living moment, not staging it:
  • "Ateşin üstünde kaynayan tencere, kenarda uyuklayan köpek"
  • Compositions should feel discovered, not composed
  • Imply off-screen presence: sounds, light sources, shadows, reflections

DOGRU:   "Omuz üstü: yaşlı ellerin açık el yazması tutması, sabah ışığı"
DOGRU:   "Alt açı: çölü kesen deve kervanı silueti, turuncu gün batımı"
DOGRU:   "timelapse: kaleye karşı gün ışığının sürüklenmesi, mevsim geçişi"
YANLIS:  "Geleneğin yaşatılması" (soyut — reddedilir)
YANLIS:  "Manevi atmosfer" (soyut — reddedilir)
YANLIS:  "Adam yürüyor" (düz kurgu — reddedilir; açı/derinlik/yansıma ekle)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ANIMATION-COMPATIBLE COMPOSITION RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Every scene will be animated. The visualNote must actively support motion:
  • ONE clear focal point — not a list of objects
  • Implied depth: foreground / midground / background always readable
  • "Frozen peak" principle: the most dramatic frame before or just after action
    ("su fışkırmak üzere" not "su fışkırıyor" — capture the tension moment)
  • WIDE scenes: horizontal composition for parallax pan
  • CLOSE scenes: single isolated detail for Ken Burns zoom
  • REFLECTIONS welcome: water surface, glass, armour, wet stone
  • SILHOUETTES welcome: figure against fire, window, dawn sky
  • FORBIDDEN: perfectly symmetrical, static, flat compositions
  • FORBIDDEN: subjects posing or facing camera (passport pose)
  • FORBIDDEN: armies/crowds neatly arranged like a theatre stage
  • FORBIDDEN: single-colour uniform backgrounds with no depth
  • PREFERRED: over-the-shoulder, through-a-gap, low-angle-with-sky, dust/smoke

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KALABALIK / ORDU ÇERÇEVELEME KURALI (KİTİKSSİK)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Bir sahnede 10+ kişi, askeri birlik veya kalabalık varsa:
Çergevedeki tüm grubu gösterme. Bunun yerine aşağıdaki 6 yöntemden BİRİNİ seç:

  1. FRAGMAN    → 3-5 figur ense yakını, arkası bulanık / silue — "mimarların ön safları"
               Visual note örneği: "3 miğferin yakın çekimi, arkada tozlu siluet denizi"

  2. YER AÇISI  → Zemine yakın kamera: ayaklar, toz, at nalları, kalkan kenarları
               Visual note örneği: "Zemin açısı: tozlu zeminde yüz binlerce ayağın adesi"

  3. YÜKSEK AÇI → Tamamen tepeden: miğferler ve mızraklar okyanus gibi, yüzler yok
               Visual note örneği: "Kuş bakışı: mızrak uçları denizi, üstten sıkışık kalabalık"

  4. TEPKİ     → Bir gözlemci’nin kalabalığı izlemesi — çocuk, yaşlı, hayvan
               Visual note örneği: "Pencere kenaırında kalabalığı izleyen ürküş müşteri"

  5. ARTİK     → Kalabalık geçtikten sonraki boş alan, toz bulutu, terk edilmiş eşyalar
               Visual note örneği: "Ordu geçtikten sonra boş kalan meydan, toz hala iniyor"

  6. DETAY     → Tek bir el, yüz, nesne — kalabalık ses/gölgeyle ima edilir
               Visual note örneği: "Sıkı tutulan mızrak sapı, parmaklar arasındaki gergin boşluk"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Write character visualDescriptions as a SCULPTOR, not a storyteller.
Every detail must be measurable, architectural, reproducible.

ANTI-HALLUCINATION RULE:
  If a character's physical appearance, ethnicity, clothing, or period details
  are NOT stated or strongly implied in the source text, you MUST write:
  "[Inferred from era/region — not stated in source]"
  at the end of the relevant field. Do NOT invent specific details with false confidence.
  It is better to say "standard nomadic steppe attire of the period" than to fabricate
  a specific garment colour that was not mentioned.

MANDATORY FIELDS (all must be present and non-empty):

  age:             "mid-40s to early 50s" — range, not a single number
  ethnicity:       Phenotypic description — facial structure, skin tone.
                   Example: "East African phenotype, dark brown-black skin,
                   high cheekbones, narrow nose bridge"
                   NEVER leave empty. Infer from era and geography if not stated.

  physicalFeatures: Face geometry ONLY.
                   Example: "Broad zygomatic arches, deep-set eyes under heavy
                   brow ridge, low nasal bridge, strong squared jaw"
                   NO adjectives of character: not "wise", "kind", "intelligent"

  hair:            Length + colour + texture (numerical where possible).
                   Example: "Dense black hair worn loose to shoulder, slightly
                   matted from travel, no oil or styling"

  beard:           Length in CM + colour + texture + shape.
                   Example: "Full beard extending 10-12cm below jaw, iron-grey
                   with white at lower edges, naturally parted, dense"
                   If no beard: "clean-shaven" or "thin adolescent stubble"

  clothing:        Every layer. Fabric type. Colour name. Construction detail.
                   Era-accurate. Example: "Rough-woven indigo cotton tunic,
                   untailored, belted with a strip of raw leather; coarse linen
                   trousers; leather sandals with two straps"

  visualDescription: ONE flowing paragraph synthesising ALL above fields.
                    This is what the AI model reads. It must be complete and
                    anchored in physical specifics.
                    END with NEGATIVE ANCHOR: "NOT [opposite build],
                    NOT [wrong beard colour], NOT [wrong clothing]"
                    DO NOT include "photorealistic", "cinematic" — the
                    prompt engine adds these automatically.

BODY ARCHITECTURE (add to visualDescription):
  Weight estimate:  "heavyset, approximately 90-100kg"
  Height:          "tall, approximately 185cm" or "short, approximately 160cm"
  Shoulders:       "broad" or "narrow and sloping"
  Posture:         "forward-hunched with age" or "rigidly upright"
  Abdomen:         "slight belly" or "lean torso" — pick one

FORBIDDEN in character descriptions:
  ✗ "Photorealistic" or "cinematic lighting" (added by prompt engine)
  ✗ "Wise", "kind", "brave", "intelligent" (psychological — not physical)
  ✗ Narrative backstory
  ✗ Leaving any mandatory field empty or writing "unknown"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCATION DESCRIPTION STANDARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

30 words maximum. English. Physical and photographable only.
Materials, scale, geographic context, dominant visual feature.

CORRECT:   "Vast semi-arid plateau, sparse dry grass, low volcanic ridges
           in middle distance, open sky, no trees within frame"
CORRECT:   "Interior of a 13th-century stone warehouse — barrel-vaulted ceiling,
           rough ashlar walls, straw on earthen floor, two narrow slit windows"
INCORRECT: "A place full of history" — abstract, rejected

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TIME CONTEXT STANDARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Maximum 5-8 time contexts total. Merge similar ones.
Only create a NEW context if era, light, or atmosphere genuinely changes.
"Location A — night" and "Location B — night (same era)" CAN be one context
if lighting and atmosphere match.

MANDATORY FIELDS:
  label:          Short English label used to link scenes. Example: "Rome — Noon"
  era:            Specific historical period. Example: "1st Century BCE Roman Republic"
  timeOfDay:      "dawn" | "morning" | "midday" | "afternoon" | "golden hour" |
                  "dusk" | "blue hour" | "night" | "deep night"
  lighting:       Describe the light as a cinematographer would — source, direction,
                  colour temperature, quality (hard/soft), shadow character.
                  NO supernatural descriptions (no "blinding white-gold", no "divine radiance")
  historicalNotes: The CURRENT physical and social state of the scene RIGHT NOW.
                  Not background history — what is VISIBLE IN THIS MOMENT?
                  Example: "The marketplace is active at peak trading hours;
                  merchants have spread their goods on reed mats; dust rises
                  from the animal pens at the eastern end"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NARRATIVE LAYER CLASSIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Assign ONE narrativeLayer to each scene:

  "historical"  → Specific historical period, culture, geography. Has era, characters, locations.
  "modern"      → Contemporary world (approximately 1980–present). Urban, global, technological.
  "scientific"  → Biology, physics, chemistry, neurology, ecology, cosmology.
                 No historical costumes. Macro photography mode.
  "universal"   → Timeless human experience (grief, love, labour, sleep, hunger).
                 No specific culture or era required. Choose one visual anchor.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VISUAL STYLE CLASSIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Assign "symbolic" ONLY for scenes depicting:
  • Supernatural or impossible physics (energy fields, frozen time, shape-shifting)
  • Spiritual manifestations, deities, cosmic forces made visible
  • Mythological events as described in their source tradition
  • Metaphors that require the image to break physical reality

Assign "scientific" for biology, physics, cosmology, anatomy scenes.

Assign "cinematic" (default) for everything else — including historical scenes,
emotional moments, and large-scale historical events (even dramatic ones).

UNCERTAIN? Default to "cinematic". Not to "symbolic".

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REQUIRED JSON OUTPUT FORMAT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Return ONLY valid JSON matching this exact schema.
No preamble, no markdown, no explanation.

{
  "characters": [
    {
      "name": "Character Name",
      "role": "Their function or title in this context",
      "isCrowd": false,
      "age": "mid-40s to early 50s",
      "ethnicity": "Phenotypic description with skin tone and facial structure",
      "physicalFeatures": "Facial geometry — bone structure, eyes, nose, jaw",
      "hair": "Length, colour, texture, style",
      "beard": "Length in cm, colour, texture — or 'clean-shaven'",
      "clothing": "Every garment layer, fabric, colour, construction",
      "visualDescription": "Complete physical anchor paragraph with negative anchor at end"
    }
  ],
  "locations": [
    {
      "name": "Location Name",
      "visualDescription": "30-word physical description — materials, scale, geography"
    }
  ],
  "timeContexts": [
    {
      "label": "Location — Time Label",
      "era": "Specific historical period",
      "season": "Season if relevant",
      "timeOfDay": "dawn | morning | midday | afternoon | golden hour | dusk | blue hour | night",
      "lighting": "Cinematographic light description — source, direction, temperature, quality",
      "weather": "Weather condition if relevant",
      "historicalNotes": "Current visible state of the scene — not background history"
    }
  ],
  "scenes": [
    {
      "sceneNumber": 1,
      "text": "Exact words from source text — do not rephrase",
      "visualNote": "10-word physical camera description",
      "narrativeLayer": "historical | modern | scientific | universal",
      "visualStyle": "cinematic | symbolic | scientific",
      "characterNames": ["Character Name"],
      "locationNames": ["Location Name"],
      "timeContextLabel": "Matching label from timeContexts"
    }
  ]
}

CRITICAL CONSTRAINTS:
  • Every scene MUST have a timeContextLabel
  • Every character MUST have all seven fields filled — NEVER leave empty or write "unknown"
  • If character details are not in the text, INFER from era, geography, and role
  • scenes[].text must be exact source words — do not paraphrase or summarise
  • Do not add scenes not implied by the source text

TEXT TO ANALYSE:
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// § 2  JSON RECOVERY UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

function cleanJsonResponse(text: string): string {
  const fenced = text.match(/```json\s*([\s\S]*?)```/);
  if (fenced) {
    text = fenced[1].trim();
  } else {
    const brace = text.indexOf('{');
    if (brace > 0) text = text.substring(brace);
    text = text.replace(/```\s*$/g, '').trim();
  }

  // Strip non-printable control characters (keep tab/LF/CR)
  text = text.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g, '');

  // Escape unescaped whitespace inside JSON strings
  text = text.replace(/"([^"\\]*(\\.[^"\\]*)*)"/g, (m) =>
    m.replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t')
  );

  try {
    JSON.parse(text);
    return text;
  } catch {
    return recoverTruncatedJson(text);
  }
}

function recoverTruncatedJson(raw: string): string {
  const lastBrace = raw.lastIndexOf('}');
  if (lastBrace <= 0) throw new Error('Cannot recover truncated JSON — no closing brace found');

  let candidate = raw.substring(0, lastBrace + 1);
  let brackets = 0, braces = 0, inStr = false, esc = false;

  for (const ch of candidate) {
    if (esc)  { esc = false; continue; }
    if (ch === '\\' && inStr) { esc = true; continue; }
    if (ch === '"') { inStr = !inStr; continue; }
    if (inStr) continue;
    if (ch === '[') brackets++;
    else if (ch === ']') brackets--;
    else if (ch === '{') braces++;
    else if (ch === '}') braces--;
  }

  candidate += ']'.repeat(Math.max(0, brackets));
  candidate += '}'.repeat(Math.max(0, braces));
  return candidate;
}

// ─────────────────────────────────────────────────────────────────────────────
// § 3  TEXT CHUNKING
// ─────────────────────────────────────────────────────────────────────────────

function splitTextIntoChunks(text: string, maxChars = 6000): string[] {
  if (text.length <= maxChars) return [text];

  const chunks: string[] = [];
  const paragraphs = text.split(/\n+/);
  let current = '';

  for (const para of paragraphs) {
    if (para.length > maxChars) {
      if (current) { chunks.push(current.trim()); current = ''; }

      const sentences = para.split(/(?<=[.!?])\s+/);
      let sentenceChunk = '';
      for (const sentence of sentences) {
        if ((sentenceChunk + ' ' + sentence).length > maxChars && sentenceChunk) {
          chunks.push(sentenceChunk.trim());
          sentenceChunk = sentence;
        } else {
          sentenceChunk = sentenceChunk ? `${sentenceChunk} ${sentence}` : sentence;
        }
      }
      current = sentenceChunk;
    } else {
      const next = current ? `${current}\n${para}` : para;
      if (next.length > maxChars && current) {
        chunks.push(current.trim());
        current = para;
      } else {
        current = next;
      }
    }
  }

  if (current.trim()) chunks.push(current.trim());
  return chunks;
}

// ─────────────────────────────────────────────────────────────────────────────
// § 4  FUZZY TEXT POSITION FINDER
//      Locates a scene's source text within the full narration for highlighting.
// ─────────────────────────────────────────────────────────────────────────────

function fuzzyFindText(
  fullText: string,
  searchStr: string,
  startIndex: number,
): { start: number; end: number } | null {
  const clean = searchStr.trim();
  if (!clean) return null;

  // Exact match from startIndex
  let idx = fullText.indexOf(clean, startIndex);
  if (idx !== -1) return { start: idx, end: idx + clean.length };

  // Exact match from beginning
  idx = fullText.indexOf(clean, 0);
  if (idx !== -1) return { start: idx, end: idx + clean.length };

  // Case-insensitive
  const lower = fullText.toLowerCase();
  const lowerSearch = clean.toLowerCase();
  idx = lower.indexOf(lowerSearch, startIndex);
  if (idx === -1) idx = lower.indexOf(lowerSearch, 0);
  if (idx !== -1) return { start: idx, end: idx + clean.length };

  // Token fuzzy match (80% threshold)
  const tokenRe = /\S+/g;
  const fullTokens: { word: string; index: number }[] = [];
  let m: RegExpExecArray | null;
  while ((m = tokenRe.exec(fullText)) !== null) {
    fullTokens.push({ word: m[0].toLowerCase().replace(/\W/g, ''), index: m.index });
  }

  const searchTokens = clean.split(/\s+/)
    .map(w => w.toLowerCase().replace(/\W/g, ''))
    .filter(w => w.length > 0);

  if (!searchTokens.length) return null;

  const threshold = Math.ceil(searchTokens.length * 0.8);
  const fromIdx   = fullTokens.findIndex(t => t.index >= Math.max(0, startIndex - 50));
  const from      = fromIdx >= 0 ? fromIdx : 0;

  const tryFrom = (start: number, end: number) => {
    for (let i = start; i <= end - searchTokens.length; i++) {
      let matches = 0;
      for (let j = 0; j < searchTokens.length; j++) {
        const ft = fullTokens[i + j]?.word ?? '';
        const st = searchTokens[j];
        if (ft === st || ft.startsWith(st) || st.startsWith(ft)) matches++;
      }
      if (matches >= threshold) {
        const s = fullTokens[i].index;
        return { start: s, end: Math.min(s + clean.length + 10, fullText.length) };
      }
    }
    return null;
  };

  return tryFrom(from, fullTokens.length) ?? tryFrom(0, from);
}

// ─────────────────────────────────────────────────────────────────────────────
// § 5  TYPE DEFINITIONS
// ─────────────────────────────────────────────────────────────────────────────

type CharacterRaw = {
  name: string;
  role?: string;
  isCrowd?: boolean;
  age?: string;
  ethnicity?: string;
  physicalFeatures?: string;
  hair?: string;
  beard?: string;
  clothing?: string;
  visualDescription?: string;
};

type LocationRaw = {
  name: string;
  visualDescription?: string;
};

type TimeContextRaw = Partial<Omit<TimeContext, 'id'>>;

type SceneRaw = {
  sceneNumber?: number;
  text?: string;
  visualNote?: string;
  narrativeLayer?: NarrativeLayer;
  visualStyle?: string;
  timeContextLabel?: string;
  characterNames?: string[];
  locationNames?: string[];
  characters?: CharacterRaw[];
  locations?: LocationRaw[];
};

type AnalysisPayload = {
  characters?: CharacterRaw[];
  locations?: LocationRaw[];
  scenes?: SceneRaw[];
  timeContexts?: TimeContextRaw[];
  timeContext?: TimeContextRaw;
};

// ─────────────────────────────────────────────────────────────────────────────
// § 6  NORMALISATION HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function normaliseLocationName(name: string): string {
  return name.toLowerCase().trim()
    .replace(/\b(the|a|an)\b/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function characterId(name: string): string {
  return `char-${name.toLowerCase().replace(/\s+/g, '-')}`;
}

function locationId(name: string): string {
  return `loc-${name.toLowerCase().replace(/\s+/g, '-')}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// § 7  SCENE CARD BUILDER
// ─────────────────────────────────────────────────────────────────────────────

function buildSceneCards(
  scenes: SceneRaw[],
  sceneNumberOffset: number,
  characterMap: Map<string, Character>,
  locationMap: Map<string, Location>,
  locationNormMap: Map<string, string>,
  timeContextLabelMap: Map<string, string>,
  fullText: string,
  searchState: { lastIndex: number },
): SceneCard[] {
  return scenes.map((scene, idx) => {
    const globalIdx  = sceneNumberOffset + idx;
    const id         = crypto.randomUUID();
    const charIds: string[]  = [];
    const locIds: string[]   = [];

    // Link characters by name
    scene.characterNames?.forEach(name => {
      const cid = characterId(name);
      if (characterMap.has(cid) && !charIds.includes(cid)) charIds.push(cid);
    });

    // Inline character definitions (sometimes AI embeds them per-scene)
    scene.characters?.forEach(char => {
      if (!char.name) return;
      const cid = characterId(char.name);
      if (!characterMap.has(cid)) {
        characterMap.set(cid, {
          id: cid, name: char.name, role: char.role,
          isCrowd: char.isCrowd ?? false,
          age: char.age, ethnicity: char.ethnicity,
          physicalFeatures: char.physicalFeatures,
          hair: char.hair, beard: char.beard, clothing: char.clothing,
          visualDescription: char.visualDescription,
        });
      }
      if (!charIds.includes(cid)) charIds.push(cid);
    });

    // Link locations by normalised name
    scene.locationNames?.forEach(name => {
      const norm = normaliseLocationName(name);
      const lid  = locationNormMap.get(norm);
      if (lid && !locIds.includes(lid)) locIds.push(lid);
    });

    scene.locations?.forEach(loc => {
      if (!loc.name) return;
      const norm = normaliseLocationName(loc.name);
      const existing = locationNormMap.get(norm);
      if (existing) {
        if (!locIds.includes(existing)) locIds.push(existing);
      } else {
        const lid = locationId(loc.name);
        locationMap.set(lid, { id: lid, name: loc.name, visualDescription: loc.visualDescription });
        locationNormMap.set(norm, lid);
        if (!locIds.includes(lid)) locIds.push(lid);
      }
    });

    // Find text position in source
    let startIndex: number | undefined;
    let endIndex: number | undefined;
    if (scene.text) {
      const match = fuzzyFindText(fullText, scene.text, searchState.lastIndex);
      if (match) {
        startIndex = match.start;
        endIndex   = match.end;
        searchState.lastIndex = match.end;
      }
    }

    const card: SceneCard = {
      id,
      sceneNumber: globalIdx + 1,
      text: scene.text ?? '',
      visualNote: scene.visualNote ?? `Scene ${globalIdx + 1}`,
      narrativeLayer: scene.narrativeLayer,
      visualStyle: resolveVisualStyle(scene),
      characterIds: charIds,
      locationIds: locIds,
      timeContextIds: [],
      startIndex,
      endIndex,
      prompts: [],
      status: 'analyzed',
      noteEditable: true,
    };

    if (scene.timeContextLabel) {
      timeContextLabelMap.set(id, scene.timeContextLabel);
    }

    return card;
  });
}

function resolveVisualStyle(scene: SceneRaw): 'cinematic' | 'symbolic' | 'scientific' | 'abstract' | undefined {
  if (scene.visualStyle === 'symbolic')   return 'symbolic';
  if (scene.visualStyle === 'scientific') return 'scientific';
  if (scene.narrativeLayer === 'scientific') return 'scientific';

  // Keyword detection for symbolic content
  const combined = `${scene.visualNote ?? ''} ${scene.text ?? ''}`.toLowerCase();
  const symbolicKeywords = [
    'energy ring', 'cosmic force', 'frozen time', 'frozen water', 'shape transforms',
    'spirit appears', 'deity descends', 'divine light', 'shape-shifts', 'metamorphosis',
    'sound wave visible', 'vibration visible', 'energy field', 'aura radiates',
  ];
  if (symbolicKeywords.some(k => combined.includes(k))) return 'symbolic';

  return 'cinematic';
}

// ─────────────────────────────────────────────────────────────────────────────
// § 8  CHUNK ANALYSER
// ─────────────────────────────────────────────────────────────────────────────

async function analyseChunk(
  chunk: string,
  targetSceneCount?: number,
): Promise<AnalysisPayload> {
  const systemPrompt = getSceneAnalysisSystemPrompt();
  
  // Inject target instruction into User Message to preserve System Prompt caching
  let userMessage = chunk;
  if (targetSceneCount) {
    userMessage = `${getSceneAnalysisTargetInstruction(targetSceneCount)}\n\n--- TEXT TO ANALYZE ---\n${chunk}`;
  }

  const raw = await aiProvider.generateContent(userMessage, systemPrompt, { operationType: 'scene_analysis' });

  let cleaned: string;
  try {
    cleaned = cleanJsonResponse(raw);
  } catch {
    cleaned = raw;
  }

  try {
    return JSON.parse(cleaned) as AnalysisPayload;
  } catch (err) {
    try {
      return JSON.parse(recoverTruncatedJson(cleaned)) as AnalysisPayload;
    } catch {
      throw new Error(`Scene analysis JSON parse failed: ${err instanceof Error ? err.message : err}`);
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// § 9  TIME CONTEXT MERGE
// ─────────────────────────────────────────────────────────────────────────────

function mergeTimeContexts(existing: TimeContext[], incoming: TimeContext[]): TimeContext[] {
  const map = new Map(existing.map(tc => [tc.label, tc]));
  incoming.forEach(tc => { if (!map.has(tc.label)) map.set(tc.label, tc); });
  return Array.from(map.values());
}

// ─────────────────────────────────────────────────────────────────────────────
// § 10  MAIN ANALYSIS FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

export async function analyzeTextIntoScenes(
  text: string,
  _apiKey?: string,
  _model?: string,
  onProgress?: (message: string) => void,
  targetSceneCount?: number,
): Promise<{
  sceneCards: SceneCard[];
  characters: Character[];
  locations: Location[];
  suggestedTimeContexts: TimeContext[];
}> {
  onProgress?.(`Preparing text... (${text.length} characters, ~${Math.round(text.split(' ').length)} words)`);

  const chunks = splitTextIntoChunks(text);
  onProgress?.(`Split into ${chunks.length} chunk(s) for analysis`);

  const characterMap       = new Map<string, Character>();
  const locationMap        = new Map<string, Location>();
  const locationNormMap    = new Map<string, string>(); // normalised name → id
  const timeContextLabelMap = new Map<string, string>(); // sceneId → label
  const allSceneCards: SceneCard[] = [];
  let suggestedTimeContexts: TimeContext[] = [];
  let sceneNumberOffset = 0;
  const searchState = { lastIndex: 0 };

  // Distribute target scene count proportionally across chunks
  const totalChars = chunks.reduce((s, c) => s + c.length, 0);
  let remainingTarget = targetSceneCount;
  
  const chunkTargets: (number | undefined)[] = chunks.map((chunk, i) => {
    if (!targetSceneCount) return undefined;
    if (chunks.length === 1) return targetSceneCount;
    
    // Proportional target
    let target = Math.round(targetSceneCount * (chunk.length / totalChars));
    
    // Ensure at least 1 scene per chunk if the total target allows it
    if (target < 1 && remainingTarget >= 1) target = 1;
    
    // Last chunk gets the remainder to ensure exact total
    if (i === chunks.length - 1) {
      return Math.max(1, remainingTarget);
    }
    
    remainingTarget -= target;
    return Math.max(1, target);
  });

  console.log(`[sceneAnalyzer] Analysis started: ${chunks.length} chunks. Targets:`, chunkTargets);
  onProgress?.(`Metin ${chunks.length} parçaya bölündü, analiz başlatılıyor...`);

  // Process chunks IN PARALLEL for massive speedup
  const chunkResults = await Promise.all(
    chunks.map(async (chunk, i) => {
      try {
        const result = await analyseChunk(chunk, chunkTargets[i]);
        onProgress?.(`Parça ${i + 1}/${chunks.length} tamamlandı (${result.scenes?.length || 0} sahne).`);
        return result;
      } catch (err) {
        console.error(`Error analyzing chunk ${i}:`, err);
        throw err;
      }
    })
  );

  for (let i = 0; i < chunkResults.length; i++) {
    const parsed = chunkResults[i];

    // Register characters
    (parsed.characters ?? []).forEach(char => {
      if (!char.name) return;
      const cid = characterId(char.name);
      if (!characterMap.has(cid)) {
        characterMap.set(cid, {
          id: cid, name: char.name, role: char.role,
          isCrowd: char.isCrowd ?? false,
          age: char.age, ethnicity: char.ethnicity,
          physicalFeatures: char.physicalFeatures,
          hair: char.hair, beard: char.beard, clothing: char.clothing,
          visualDescription: char.visualDescription,
        });
      }
    });

    // Register locations
    (parsed.locations ?? []).forEach(loc => {
      if (!loc.name) return;
      const norm = normaliseLocationName(loc.name);
      if (!locationNormMap.has(norm)) {
        const lid = locationId(loc.name);
        locationMap.set(lid, { id: lid, name: loc.name, visualDescription: loc.visualDescription });
        locationNormMap.set(norm, lid);
      }
    });

    // Build location normalised index (for card builder)
    const locNormSnap = new Map(locationNormMap);

    // Reset search anchor to start of this chunk
    const chunkStart = text.indexOf(chunks[i]);
    if (chunkStart !== -1) searchState.lastIndex = chunkStart;

    const cards = buildSceneCards(
      parsed.scenes ?? [],
      sceneNumberOffset,
      characterMap,
      locationMap,
      locNormSnap,
      timeContextLabelMap,
      text,
      searchState,
    );

    allSceneCards.push(...cards);
    sceneNumberOffset += (parsed.scenes ?? []).length;

    onProgress?.(`${cards.length} scene cards built from chunk ${i + 1}`);

    // Collect time contexts
    const rawContexts: TimeContextRaw[] =
      Array.isArray(parsed.timeContexts) && parsed.timeContexts.length > 0
        ? parsed.timeContexts
        : parsed.timeContext?.label ? [parsed.timeContext] : [];

    const chunkContexts: TimeContext[] = rawContexts
      .filter(tc => tc.label)
      .map(tc => ({
        id: `tc-${crypto.randomUUID()}`,
        label: tc.label!,
        era: tc.era,
        season: tc.season,
        timeOfDay: tc.timeOfDay,
        lighting: tc.lighting,
        weather: tc.weather,
        historicalNotes: tc.historicalNotes,
      }));

    suggestedTimeContexts = mergeTimeContexts(suggestedTimeContexts, chunkContexts);
  }

  // Link scene cards to time contexts
  const labelToId = new Map(suggestedTimeContexts.map(tc => [tc.label, tc.id]));
  for (const card of allSceneCards) {
    const label = timeContextLabelMap.get(card.id);
    if (label) {
      const tcId = labelToId.get(label);
      if (tcId) card.timeContextIds = [tcId];
    }
  }

  onProgress?.(`Analysis complete — ${allSceneCards.length} scenes, ${characterMap.size} characters, ${locationMap.size} locations`);

  return {
    sceneCards: allSceneCards,
    characters: Array.from(characterMap.values()),
    locations: Array.from(locationMap.values()),
    suggestedTimeContexts,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// § 11  EPISODE VISUAL BRIEF GENERATOR
// ─────────────────────────────────────────────────────────────────────────────

export async function generateEpisodePrompt(
  documentText: string,
  characters: Character[],
  locations: Location[],
): Promise<string> {
  const charSummary = characters.slice(0, 5)
    .map(c => `${c.name}${c.role ? ` (${c.role})` : ''}`).join(', ');
  const locSummary  = locations.slice(0, 5).map(l => l.name).join(', ');

  const systemPrompt = `You are a world-class documentary film art director.
You will be given a narration excerpt, character list, and location list from a documentary episode.
Your task: write a comprehensive VISUAL STYLE BRIEF for this episode.

The brief must cover:
  • Overall visual tone and atmosphere (cinematographer references welcome)
  • Colour palette and contrast intent
  • Light character (warm/cool, hard/soft, direction)
  • Camera language (intimate close work vs. epic wide)
  • Era and cultural aesthetic accuracy notes
  • Dominant texture and material character
  • Emotional and psychological tone

Write in English. 150–200 words. Flowing paragraphs, not bullet points.
Written as a cinematography brief — usable directly as a Midjourney / Stable Diffusion master prompt.
Do not mention specific AI tool names in the brief itself.`;

  const userMessage = `Source narration (excerpt):\n${documentText.substring(0, 1500)}

Characters: ${charSummary || 'Not specified'}
Locations: ${locSummary || 'Not specified'}

Write the visual style brief:`;

  return (await aiProvider.generateContent(userMessage, systemPrompt)).trim();
}

export async function generateEpisodePromptExplanation(
  episodePrompt: string,
): Promise<string> {
  const systemPrompt = `You are a professional documentary director and translator.
You are given an English visual style brief written for AI image generation.
Write a concise summary in the SAME LANGUAGE as the brief (or in the user's preferred language)
that explains the visual vision to a production team or client — not a technical audience.

Rules:
  • Do not translate literally — summarise fluidly.
  • Cover: colour palette, light style, camera language, and general atmosphere.
  • Maximum 2-3 sentences, 40-60 words.
  • Professional tone.`;

  const userMessage = `Visual Style Brief:\n${episodePrompt}\n\nWrite a concise non-technical summary:`;
  return (await aiProvider.generateContent(userMessage, systemPrompt)).trim();
}

export async function reviseEpisodePrompt(
  currentPrompt: string,
  instruction: string,
): Promise<string> {
  const systemPrompt = `You are a world-class documentary film art director.
You are given an existing English visual style brief and a revision instruction.

Task:
  • Apply the instruction while preserving the brief's structure and quality.
  • Only change what the instruction specifies.
  • Output: revised English brief only. 150–200 words. No explanation, no markdown.`;

  const userMessage = `Current Visual Style Brief:\n${currentPrompt || '(None — write from scratch)'}

Revision instruction:\n"${instruction}"

Output only the revised brief:`;

  return (await aiProvider.generateContent(userMessage, systemPrompt, {
    operationType: 'episode_style_revision',
  })).trim();
}
