import React, { useState, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PanelGroup, Panel, PanelResizeHandle } from 'react-resizable-panels';
import {
  Sparkles,
  Send,
  Settings,
  ArrowLeft,
  Loader2,
  History,
  ChevronRight,
  Bot,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { aiProvider } from '@/lib/aiProvider';
import { getStackRecommendations, ToolRecommendation, StackAIResponse } from '@/lib/stackAiApi';
import { supabase } from '@/lib/supabase';
import { PillGroup } from '@/components/StackAI/PillGroup';
import { ToolCard } from '@/components/StackAI/ToolCard';
import { StackPanel } from '@/components/StackAI/StackPanel';
import { useToast } from '@/hooks/use-toast';

interface Message {
  role: 'user' | 'assistant';
  content: string;
  response?: StackAIResponse;
}

interface SessionRecord {
  id: string;
  app_idea: string;
  created_at: string;
}

function exportToMarkdown(tools: ToolRecommendation[]): string {
  const grouped = tools.reduce<Record<string, ToolRecommendation[]>>((acc, t) => {
    if (!acc[t.category]) acc[t.category] = [];
    acc[t.category].push(t);
    return acc;
  }, {});

  const lines: string[] = [
    '# My Stack',
    '',
    `> Generated by Stack.AI on ${new Date().toLocaleDateString()}`,
    '',
  ];

  for (const [category, catTools] of Object.entries(grouped)) {
    lines.push(`## ${category}`, '');
    for (const tool of catTools) {
      lines.push(`### [${tool.name}](${tool.url})`);
      lines.push(`- **Free tier**: ${tool.freeTier}`);
      lines.push(`- ${tool.description}`);
      if (tool.tags.length > 0) {
        lines.push(`- **Tags**: ${tool.tags.join(', ')}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

export default function StackAI() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();

  const [initialized, setInitialized] = useState(false);
  const [initError, setInitError] = useState<string | null>(null);

  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);
  const [context, setContext] = useState<string[]>([]);

  const [currentTools, setCurrentTools] = useState<ToolRecommendation[]>([]);
  const [stackTools, setStackTools] = useState<ToolRecommendation[]>([]);

  const [sessions, setSessions] = useState<SessionRecord[]>([]);
  const [activeTab, setActiveTab] = useState<'chat' | 'history'>('chat');

  const chatEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (!user) return;
    aiProvider
      .initialize(user.id)
      .then(() => setInitialized(true))
      .catch((err) => {
        console.error('Failed to initialize AI provider:', err);
        setInitError('Failed to load API keys. Please check Settings.');
        setInitialized(true);
      });

    loadSessions();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  async function loadSessions() {
    if (!user) return;
    const { data } = await supabase
      .from('stack_sessions')
      .select('id, app_idea, created_at')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(20);
    if (data) setSessions(data as SessionRecord[]);
  }

  async function saveSession(appIdea: string, ctx: string[]) {
    if (!user) return;
    await supabase.from('stack_sessions').insert({
      user_id: user.id,
      app_idea: appIdea,
      context: ctx,
    });
    loadSessions();
  }

  const handleSend = useCallback(
    async (overrideInput?: string) => {
      const text = (overrideInput ?? input).trim();
      if (!text || loading) return;

      setInput('');
      setLoading(true);

      const userMsg: Message = { role: 'user', content: text };
      setMessages((prev) => [...prev, userMsg]);

      const newContext = [...context, text];

      try {
        const response = await getStackRecommendations(text, context);

        const assistantMsg: Message = {
          role: 'assistant',
          content: response.summary,
          response,
        };

        setMessages((prev) => [...prev, assistantMsg]);
        setCurrentTools(response.tools);
        setContext(newContext);

        if (messages.length === 0) {
          await saveSession(text, newContext);
        }
      } catch (err) {
        console.error('Stack AI error:', err);
        const errMsg =
          err instanceof Error ? err.message : 'Failed to get recommendations.';
        setMessages((prev) => [
          ...prev,
          { role: 'assistant', content: `Error: ${errMsg}` },
        ]);
        toast({ title: 'Error', description: errMsg, variant: 'destructive' });
      } finally {
        setLoading(false);
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [input, loading, context, messages.length, toast]
  );

  function handlePillSelect(question: string) {
    handleSend(question);
  }

  function handleAddTool(tool: ToolRecommendation) {
    setStackTools((prev) => {
      if (prev.find((t) => t.name === tool.name)) return prev;
      return [...prev, tool];
    });
    toast({
      title: `${tool.name} added`,
      description: `Added to your stack under ${tool.category}`,
    });
  }

  function handleRemoveTool(name: string) {
    setStackTools((prev) => prev.filter((t) => t.name !== name));
  }

  function handleExport() {
    const md = exportToMarkdown(stackTools);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'stack.md';
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: 'Exported!', description: 'stack.md downloaded.' });
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  }

  const lastAssistantMsg = [...messages].reverse().find((m) => m.role === 'assistant');
  const followUpQuestions = lastAssistantMsg?.response?.followUpQuestions ?? [];

  if (!initialized) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="h-6 w-6 text-violet-400 animate-spin" />
      </div>
    );
  }

  return (
    <div className="h-screen bg-background flex flex-col overflow-hidden">
      {/* Top bar */}
      <header className="flex items-center justify-between px-4 py-3 border-b border-white/8 shrink-0">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/dashboard')}
            className="text-muted-foreground hover:text-foreground transition-colors p-1 rounded"
          >
            <ArrowLeft className="h-4 w-4" />
          </button>
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-violet-500 to-purple-700 flex items-center justify-center">
              <Sparkles className="h-3.5 w-3.5 text-white" />
            </div>
            <span className="font-bold text-sm tracking-tight">Stack.AI</span>
            <span className="text-xs text-muted-foreground hidden sm:inline">
              Free tool advisor for developers
            </span>
          </div>
        </div>
        <button
          onClick={() => navigate('/settings')}
          className="text-muted-foreground hover:text-foreground transition-colors p-1 rounded"
        >
          <Settings className="h-4 w-4" />
        </button>
      </header>

      {initError && (
        <div className="bg-red-500/10 border-b border-red-500/20 px-4 py-2 text-xs text-red-400">
          {initError} —{' '}
          <button
            onClick={() => navigate('/settings')}
            className="underline hover:no-underline"
          >
            Go to Settings
          </button>
        </div>
      )}

      {/* Three-column layout */}
      <div className="flex-1 overflow-hidden">
        {/* Desktop: three columns */}
        <div className="hidden md:flex h-full">
          <PanelGroup direction="horizontal" className="h-full">
            {/* Left: Session History */}
            <Panel defaultSize={20} minSize={15} maxSize={30}>
              <div className="h-full flex flex-col border-r border-white/8">
                <div className="flex items-center gap-2 p-4 border-b border-white/8">
                  <History className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">History</span>
                </div>
                <div className="flex-1 overflow-y-auto scrollbar-thin p-2 space-y-1">
                  {sessions.length === 0 ? (
                    <p className="text-xs text-muted-foreground text-center py-8 px-3">
                      Your past sessions will appear here
                    </p>
                  ) : (
                    sessions.map((s) => (
                      <button
                        key={s.id}
                        className="w-full text-left px-3 py-2 rounded-lg hover:bg-white/5 transition-colors group"
                      >
                        <p className="text-xs text-foreground truncate group-hover:text-violet-300 transition-colors">
                          {s.app_idea}
                        </p>
                        <p className="text-xs text-muted-foreground/60 mt-0.5">
                          {new Date(s.created_at).toLocaleDateString()}
                        </p>
                      </button>
                    ))
                  )}
                </div>
              </div>
            </Panel>

            <PanelResizeHandle className="w-px bg-white/8 hover:bg-violet-500/40 transition-colors" />

            {/* Center: Chat */}
            <Panel defaultSize={55} minSize={35}>
              <div className="h-full flex flex-col">
                <div className="flex-1 overflow-y-auto scrollbar-thin p-4 space-y-6">
                  {messages.length === 0 && (
                    <motion.div
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="flex flex-col items-center justify-center h-full text-center py-16 px-8"
                    >
                      <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-violet-500/20 to-purple-700/20 border border-violet-500/30 flex items-center justify-center mb-4">
                        <Bot className="h-7 w-7 text-violet-400" />
                      </div>
                      <h2 className="text-lg font-semibold text-foreground mb-2">
                        Describe your app idea
                      </h2>
                      <p className="text-sm text-muted-foreground max-w-sm">
                        Tell Stack.AI what you&apos;re building and get free tool
                        recommendations instantly.
                      </p>
                      <div className="mt-6 flex flex-wrap gap-2 justify-center">
                        {[
                          'SaaS with auth and payments',
                          'Real-time chat app',
                          'E-commerce store',
                          'Portfolio with blog',
                        ].map((example) => (
                          <button
                            key={example}
                            onClick={() => handleSend(example)}
                            className="text-xs px-3 py-1.5 rounded-full border border-white/10 bg-white/5 text-muted-foreground hover:bg-violet-500/10 hover:border-violet-500/30 hover:text-violet-300 transition-all"
                          >
                            {example}
                          </button>
                        ))}
                      </div>
                    </motion.div>
                  )}

                  <AnimatePresence initial={false}>
                    {messages.map((msg, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 8 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.2 }}
                        className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        {msg.role === 'assistant' && (
                          <div className="w-6 h-6 rounded-md bg-gradient-to-br from-violet-500 to-purple-700 flex items-center justify-center shrink-0 mt-0.5">
                            <Sparkles className="h-3 w-3 text-white" />
                          </div>
                        )}
                        <div
                          className={`max-w-[85%] space-y-3 ${
                            msg.role === 'user' ? 'items-end' : 'items-start'
                          } flex flex-col`}
                        >
                          <div
                            className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
                              msg.role === 'user'
                                ? 'bg-violet-500/20 text-foreground border border-violet-500/30 rounded-br-sm'
                                : 'bg-white/5 border border-white/8 rounded-bl-sm text-foreground'
                            }`}
                          >
                            {msg.content}
                          </div>

                          {msg.role === 'assistant' && msg.response && (
                            <div className="w-full space-y-2">
                              {msg.response.tools.map((tool, ti) => (
                                <ToolCard
                                  key={tool.name}
                                  tool={tool}
                                  index={ti}
                                  added={stackTools.some((t) => t.name === tool.name)}
                                  onAdd={handleAddTool}
                                />
                              ))}
                            </div>
                          )}
                        </div>
                      </motion.div>
                    ))}
                  </AnimatePresence>

                  {loading && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="flex items-center gap-3"
                    >
                      <div className="w-6 h-6 rounded-md bg-gradient-to-br from-violet-500 to-purple-700 flex items-center justify-center shrink-0">
                        <Sparkles className="h-3 w-3 text-white" />
                      </div>
                      <div className="flex gap-1 items-center bg-white/5 border border-white/8 rounded-2xl px-4 py-3">
                        {[0, 1, 2].map((i) => (
                          <motion.span
                            key={i}
                            className="w-1.5 h-1.5 rounded-full bg-violet-400"
                            animate={{ scale: [1, 1.4, 1], opacity: [0.4, 1, 0.4] }}
                            transition={{
                              duration: 0.8,
                              repeat: Infinity,
                              delay: i * 0.15,
                            }}
                          />
                        ))}
                      </div>
                    </motion.div>
                  )}

                  <div ref={chatEndRef} />
                </div>

                {/* Follow-up pills */}
                {followUpQuestions.length > 0 && !loading && (
                  <div className="px-4 py-2 border-t border-white/8">
                    <PillGroup
                      questions={followUpQuestions}
                      onSelect={handlePillSelect}
                      disabled={loading}
                    />
                  </div>
                )}

                {/* Input */}
                <div className="p-4 border-t border-white/8">
                  <div className="flex gap-2 items-end">
                    <textarea
                      ref={inputRef}
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={handleKeyDown}
                      placeholder="Describe your app idea…"
                      rows={1}
                      className="flex-1 resize-none bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:border-violet-500/60 focus:bg-violet-500/5 transition-all scrollbar-thin"
                      style={{ maxHeight: '120px' }}
                      onInput={(e) => {
                        const el = e.currentTarget;
                        el.style.height = 'auto';
                        el.style.height = `${Math.min(el.scrollHeight, 120)}px`;
                      }}
                      disabled={loading}
                    />
                    <motion.button
                      whileTap={{ scale: 0.92 }}
                      onClick={() => handleSend()}
                      disabled={loading || !input.trim()}
                      className="shrink-0 w-9 h-9 rounded-xl bg-violet-500 hover:bg-violet-400 disabled:bg-violet-500/30 disabled:cursor-not-allowed flex items-center justify-center transition-colors"
                    >
                      {loading ? (
                        <Loader2 className="h-4 w-4 text-white animate-spin" />
                      ) : (
                        <Send className="h-4 w-4 text-white" />
                      )}
                    </motion.button>
                  </div>
                </div>
              </div>
            </Panel>

            <PanelResizeHandle className="w-px bg-white/8 hover:bg-violet-500/40 transition-colors" />

            {/* Right: Stack Panel */}
            <Panel defaultSize={25} minSize={18} maxSize={35}>
              <StackPanel
                tools={stackTools}
                onRemove={handleRemoveTool}
                onExport={handleExport}
              />
            </Panel>
          </PanelGroup>
        </div>

        {/* Mobile: tabbed layout */}
        <div className="flex md:hidden flex-col h-full">
          <div className="flex border-b border-white/8 shrink-0">
            {(['chat', 'history'] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`flex-1 py-2.5 text-xs font-medium transition-colors capitalize ${
                  activeTab === tab
                    ? 'text-violet-300 border-b-2 border-violet-500'
                    : 'text-muted-foreground'
                }`}
              >
                {tab === 'chat' ? (
                  <span className="flex items-center justify-center gap-1.5">
                    <Sparkles className="h-3 w-3" />
                    Chat
                  </span>
                ) : (
                  <span className="flex items-center justify-center gap-1.5">
                    <History className="h-3 w-3" />
                    History
                  </span>
                )}
              </button>
            ))}
            <button
              onClick={() => setActiveTab('chat' as never)}
              className="px-4 py-2.5 text-xs text-muted-foreground border-l border-white/8"
            >
              Stack ({stackTools.length})
            </button>
          </div>

          <div className="flex-1 overflow-hidden">
            {activeTab === 'history' ? (
              <div className="h-full overflow-y-auto scrollbar-thin p-3 space-y-1">
                {sessions.length === 0 ? (
                  <p className="text-xs text-muted-foreground text-center py-8">
                    No sessions yet
                  </p>
                ) : (
                  sessions.map((s) => (
                    <button
                      key={s.id}
                      className="w-full text-left px-3 py-2 rounded-lg hover:bg-white/5 transition-colors flex items-center gap-2"
                    >
                      <div className="flex-1 min-w-0">
                        <p className="text-xs text-foreground truncate">{s.app_idea}</p>
                        <p className="text-xs text-muted-foreground/60">
                          {new Date(s.created_at).toLocaleDateString()}
                        </p>
                      </div>
                      <ChevronRight className="h-3 w-3 text-muted-foreground shrink-0" />
                    </button>
                  ))
                )}
              </div>
            ) : (
              <div className="h-full flex flex-col">
                <div className="flex-1 overflow-y-auto scrollbar-thin p-3 space-y-4">
                  {messages.length === 0 && (
                    <div className="flex flex-col items-center justify-center py-12 text-center px-4">
                      <Bot className="h-8 w-8 text-violet-400/50 mb-3" />
                      <p className="text-sm text-muted-foreground">Describe your app idea below</p>
                    </div>
                  )}
                  <AnimatePresence initial={false}>
                    {messages.map((msg, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 6 }}
                        animate={{ opacity: 1, y: 0 }}
                        className={`flex gap-2 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                      >
                        <div className={`max-w-[90%] space-y-2 flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                          <div className={`rounded-2xl px-3 py-2 text-xs leading-relaxed ${msg.role === 'user' ? 'bg-violet-500/20 border border-violet-500/30' : 'bg-white/5 border border-white/8'}`}>
                            {msg.content}
                          </div>
                          {msg.role === 'assistant' && msg.response && (
                            <div className="w-full space-y-1.5">
                              {msg.response.tools.map((tool, ti) => (
                                <ToolCard
                                  key={tool.name}
                                  tool={tool}
                                  index={ti}
                                  added={stackTools.some((t) => t.name === tool.name)}
                                  onAdd={handleAddTool}
                                />
                              ))}
                            </div>
                          )}
                        </div>
                      </motion.div>
                    ))}
                  </AnimatePresence>
                  {loading && (
                    <div className="flex items-center gap-2">
                      <div className="flex gap-1 bg-white/5 border border-white/8 rounded-2xl px-3 py-2.5">
                        {[0, 1, 2].map((i) => (
                          <motion.span key={i} className="w-1.5 h-1.5 rounded-full bg-violet-400" animate={{ scale: [1, 1.4, 1] }} transition={{ duration: 0.8, repeat: Infinity, delay: i * 0.15 }} />
                        ))}
                      </div>
                    </div>
                  )}
                  <div ref={chatEndRef} />
                </div>
                {followUpQuestions.length > 0 && !loading && (
                  <div className="px-3 py-2 border-t border-white/8">
                    <PillGroup questions={followUpQuestions} onSelect={handlePillSelect} disabled={loading} />
                  </div>
                )}
                <div className="p-3 border-t border-white/8">
                  <div className="flex gap-2 items-end">
                    <textarea
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={handleKeyDown}
                      placeholder="Describe your app…"
                      rows={1}
                      className="flex-1 resize-none bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-xs text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:border-violet-500/60 transition-all"
                      disabled={loading}
                    />
                    <motion.button
                      whileTap={{ scale: 0.92 }}
                      onClick={() => handleSend()}
                      disabled={loading || !input.trim()}
                      className="shrink-0 w-8 h-8 rounded-xl bg-violet-500 hover:bg-violet-400 disabled:bg-violet-500/30 flex items-center justify-center transition-colors"
                    >
                      <Send className="h-3.5 w-3.5 text-white" />
                    </motion.button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
